function refpath = hybrid_A(start, goal, map)

ss = stateSpaceSE2;
ss.StateBounds = [map.XWorldLimits; map.YWorldLimits; [-pi pi]];
sv = validatorOccupancyMap(ss);
sv.Map = map;

% modified
planner = plannerHybridAStar(sv, ...
                             MinTurningRadius=2.65,...
                             NumMotionPrimitives=7,...
                             AnalyticExpansionInterval=3,...
                             MotionPrimitiveLength=1,...
                             InterpolationDistance=0.4);

% origin
% planner = plannerHybridAStar(sv, ...
%                              MinTurningRadius=3.68,...
%                              NumMotionPrimitives=7,...
%                              AnalyticExpansionInterval=3,...
%                              MotionPrimitiveLength=1,...
%                              InterpolationDistance=0.4);

refpath = plan(planner, start, goal); 