function dxdt = sys_h(x, u, prob_info)
        L = 2; 
        % L = 1.5;
        wp = prob_info.wp;
        r1 = prob_info.goal(1,1);
        r2 = prob_info.goal(2,1);
    
        dxdt = [x(4,1)*cos(x(3,1));...
                x(4,1)*sin(x(3,1));...
                (x(4,1)/L)*tan(u(1,1));...
                u(2,1);...
                0.5*u(1,1)^2 + 0.5*u(2,1)^2 + wp*(r1-x(1,1))^2 + wp*(r2-x(2,1))^2];
    end